[build]
  publish = "out"
  command = "chmod +x scripts/netlify-build.sh && scripts/netlify-build.sh"
  
[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_VERSION = "10.8.2"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"
  NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
